version: '3.4'
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            -  "8080:80"
        volumes:
            - ./:/var/www/html
            - ./_docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
          - php
    php:
        container_name: php
        build:
          context: ./_docker/php
        volumes:
            - ./:/var/www/html
        links:
          - mysql
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myhammer
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
